### PR TITLE
Relax R dependency

### PR DESCRIPTION
**Pull request by krlmlr**
to support standard check workflow.

### CODE REVIEW

**Comment by christophsax** [comment]
We needed R >= 4, because we use raw strings in the [`cd_page_title()`](https://github.com/cynkra/indiedown/blob/main/inst/mypackage/R/cd_page_title.R). rcc fails now on old versions, as expected.

**Comment by krlmlr** [comment]
Can we get rid of the raw strings for now, if it's only one instance?

**Comment by krlmlr** [comment]
Perhaps we can use two versions, one for R >= 4.0, one for R < 4.0?

**Comment by christophsax** [comment]
The raw strings are what makes writing LaTeX in R easy, they are quite central here. 

We used an alternative function that read LaTeX from `.tex` files for a project. Sligthly more complicated than the raw strings, but with the same benefit - to write LaTeX code as it is.

We could have both and depend on the R version, but it would make it more complicated and harder to document. After all,`cd_page_title()` is a boilerplate for all `cd_` functions.

We discussed this on release and decided against it. 8 month later, the arguments against supporting such an old version is even stronger.

**Pull request merged**
